name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger workflow on semantic version tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/angular-app
          tags: |
            type=semver,pattern={{version}}
            type=latest

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t ${{ steps.meta.outputs.tags }} angular-site/

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ steps.meta.outputs.tags }}
